### ISSUE TITLE
PROPOSAL to cache imported modules

### ISSUE THREAD

**Issue by cindRoberta** [tc39/proposal-module-attributes#50]
currently on Deno, it's done like this:

```javascript
// main.ts
import "https://deno.land/std/examples/welcome.ts";  
// output: Welcome to Deno 🦕
```

the file is cached in .cache/deno/gen/https/deno.land/std/examples/welcome.ts.js

my ideia is, the main.ts above wouldn't be cached that way

to cache would be like this:

________________________________________________________________________

to cache fragmented on .cache/deno/deps you could do like this:

```javascript
// main.ts
import "https://deno.land/std/examples/welcome.ts" cachefragmentedon ".cache/deno/deps/";
// output: Welcome to Deno 🦕
```

this would be cached on .cache/deno/deps/https/deno.land/std/examples/welcome.ts.js

________________________________________________________________________

to cache on a folder inside .cache/deno, you could do like this:

```javascript
// main.ts
import "https://deno.land/std/examples/welcome.ts" cacheon ".cache/deno/deps/module/version/";
// output: Welcome to Deno 🦕
```

this would be cached on .cache/deno/deps/module/version/welcome.ts.js

________________________________________________________________________

to cache fragmented in other folder out of .cache/deno/deps, would be:

```javascript
// main.ts
import "https://deno.land/std/examples/welcome.ts" cachefragmentedon "/home/user/folder/";
// output: Welcome to Deno 🦕
```

this would be cached on /home/user/folder/https/deno.land/std/examples/welcome.ts.js

________________________________________________________________________

to cache in other folder out of .cache/deno, would be:

```javascript
// main.ts
import "https://deno.land/std/examples/welcome.ts" cacheon "/home/user/folder/module/version/";
// output: Welcome to Deno 🦕
```

this would be cached on /home/user/folder/module/version/welcome.ts.js

**Comment by MylesBorins** [comment]
@cindRoberta ecma262 does not have any concept of a file system. Further this proposal outlines a mechanism for attributes, but it would still be up to the embedder (such as node or deno) to implement the attributes (and hopefully keep things consistent across the ecosystem.)

The feature you are requesting is out of scope for this repo and ecma262, and would likely make more sense as a feature request for node / demo / browsers.

TBH, I would not likely be very supportive of something like this in node.js, but would definitely give it more time and discussion in the appropriate venue 

Closing this for now, but feel free to ask questions
